services:
  redis:
    ports:
      - "6379:6379"

  mongo1:
    mem_limit: 512m
    ports:
      - "27017:27017"

  mongo2:
    mem_limit: 512m
    ports:
      - "27018:27017"

  mongo3:
    mem_limit: 512m
    ports:
      - "27019:27017"

  postgres:
    ports:
      - "5432:5432"

  sandbox-executor:
    mem_limit: 512m
    cpus: 1.0

  api-gateway:
    environment:
      GITHUB_PROBLEMS_LOCAL_DIR: /problems-repo
    volumes:
      - ../m_sql_studio_problems:/problems-repo:ro

  api-gateway-b:
    environment:
      GITHUB_PROBLEMS_LOCAL_DIR: /problems-repo
    volumes:
      - ../m_sql_studio_problems:/problems-repo:ro
