#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE $SANDBOX_PG_USER WITH
LOGIN PASSWORD '$SANDBOX_PG_PASSWORD'
NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;

GRANT CONNECT ON DATABASE "$POSTGRES_DB"
TO $SANDBOX_PG_USER;

GRANT TEMPORARY ON DATABASE "$POSTGRES_DB"
TO $SANDBOX_PG_USER;

REVOKE ALL ON DATABASE "$POSTGRES_DB"
FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

REVOKE CREATE ON DATABASE "$POSTGRES_DB"
FROM $SANDBOX_PG_USER;
EOSQL
